### ISSUE TITLE
Creating more than ~30 regions make SIGRun stutter/freeze

### ISSUE THREAD

**Issue by RaphaelWimmer** [PDA-UR/Sketchable-Interaction#224]
If one adds more than ~30 regions (tested with deletion and preview), CPU usage spikes and moving regions becomes slow/stuttery. From about 50 regions on, screen update rate becomes extremely slow (<< 0.1 fps) on my computer.
The more regions one deletes again, the more responsive SIGRun becomes again. 

Steps to reproduce: add the following function to StartSIGRun.py and call it from `on_startup()`:

```
  def add_many_regions(num = 100, area_width= 1200, area_height=600):
      left = (PySIStartup.PySIStartup.context_dimensions()[0] - area_width) // 2
      top = (PySIStartup.PySIStartup.context_dimensions()[1] - area_height) // 2
      num_h = math.ceil(math.sqrt(num / (area_width/area_height)))
      num_w = math.floor(num/num_h)
      print(f"creating region matrix: {num_w}, {num_h}")
      for i in range(num):
          row = i // num_w
          col = i % num_w
          print(f"Creating region {i}: row {row}, col {col}")
          x = col * (area_width // num_w) + left
          y = row * (area_height // num_h) + top
          w = int(area_width // num_w * 0.9)
          h = int(area_height // num_h * 0.9)
          r_shape = [[x,y], [x, y+h], [x+w, y+h], [x+w, y]]
          PySIStartup.PySIStartup.create_region_by_id(r_shape, PySIEffect.EffectType.SI_DELETION, {})
```

**Comment by HahnJuergen** [comment]
applying above scenario on my machine yields no observable stuttering with 30 or 50 regions.
100 regions still works sufficiently on my machine.
125 yields unusable performance however
