### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by RaphaelWimmer** [PDA-UR/Sketchable-Interaction#294]
The readme file should contain information on how to build the application.

E.g., (not sure about all required packages:

```
sudo apt install libboost-system1.71-dev libboost-python1.71-dev libboost-filesystem1.71-dev libglm-dev libtbb-dev 
mkdir build
cd build
cmake ..
make
```

**Comment by HahnJuergen** [comment]
build instructions were added to the readme in master branch
